version: '3.3'
services:
    nginx:
        container_name: nginx
        ports:
            - '80:80'
        volumes:
            - '/home/ubuntu/poc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
        networks:
          - mynetwork
        image: nginx
        depends_on:
            - smppnode
    
    smppnode:
        container_name: smpp_proxy_server
        networks:
          - mynetwork
        image: smppnode
        restart: always
        depends_on:
            - rabbitmq

    rabbitmq:
        container_name: rabbitmq
        ports:
            - '5672:5672'
            - '15672:15672'
        networks:
          - mynetwork
        image: 'rabbitmq:3-management'

    smppclient:
        container_name: smpp_client
        networks:
          - mynetwork
        image: smppclient
        restart: always
        depends_on:
            - rabbitmq

networks:
    mynetwork:
